filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h

https://shapr3d.atlassian.net/browse/GFX-723
The [`import()` API on `filament::Texture`](https://github.com/shapr3d/filament/blob/8c8871addadbf23e551c184c54fcc516d71866ad/filament/include/filament/Texture.h#L238) allows a Metal texture object to be injected into a Filament texture. After import, the driver checks that provided properties of the texture match the actual values. 
This limits the possible formats of importable Metal textures, because certain formats such as BGRA8 are [not available in Filament](https://github.com/shapr3d/filament/blob/8c8871addadbf23e551c184c54fcc516d71866ad/filament/backend/include/backend/DriverEnums.h#L448). This PR loosens the assert condition to a channel order invariant equality. Since the two formats behave identically when it comes to shader reads …

[GFX-723] Ignore channel order of imported textures (Metal)

---

filament/backend/include/backend/MetalPlatform.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalPlatform.mm

https://shapr3d.atlassian.net/browse/GFX-723
As discussed in https://github.com/google/filament/pull/4007#discussion_r638145082, `MetalPlatform` is designed to allow users to provide a `MTLDevice` and/or `MTLCommandQueue` of their choice. This PR makes `MetalPlaform.h` file accessible to any user of the Filament library.
We intend to make Filament graphics commands a part of our existing render loop, and the correct ordering of encoded commands must be ensured. Ordering guarantees are only provided within a command queue, therefore rendering code inside and outside Filament must use the same queue.
Manual 💁‍♂️
Tested by subclassing `MetalPlatform`, returning our single Metal device and its single queue, then rendered a scene.

[GFX-723] Make `MetalPlatform` header public

---

filament/include/filament/Skybox.h
filament/src/Skybox.cpp
filament/src/details/Skybox.h
filament/src/materials/skybox.mat
libs/viewer/include/viewer/Settings.h
libs/viewer/src/Settings.cpp
libs/viewer/src/SimpleViewer.cpp

[GFX-826](https://shapr3d.atlassian.net/browse/GFX-826) Modify Filament's Skybox class to support gradients
[GFX-827](https://shapr3d.atlassian.net/browse/GFX-827) Modify Filament's skybox material to support gradients
Added a combo box under the "Scene" header to choose background (solid color, gradient, environment). Modified the `Skybox` classes and material definition to support rendering a gradient.
Right now it uses oklab color space to do the blending, as there is available example code to convert from/to linear sRGB, and was very simple to integrate.
Will be reviewed and fine tuned when integrated into Shapr3D Visualization tool.
Filament Skybox classes and skybox.mat material definition.
Gradient background in GLTF Viewer (in this branch), with color picker for choosing blend …

[GFX-826] Add gradient support to Skybox class, material definition and viewer UI

---

filament/backend/include/backend/DriverEnums.h
filament/src/components/LightManager.cpp
libs/gltfio/src/MaterialGenerator.cpp
shaders/src/brdf.fs
shaders/src/light_directional.fs
shaders/src/light_indirect.fs
shaders/src/light_punctual.fs
shaders/src/material_inputs.fs
shaders/src/shading_model_cloth.fs
shaders/src/shading_model_standard.fs
shaders/src/shading_model_subsurface.fs

[GFX-807](https://shapr3d.atlassian.net/browse/GFX-807)
There have been a number of changes that we made to Filament based on artist feedback. This PR contains the most important ones to reach our M6 milestone:
* specular intensity scaler for indirect and direct lighting
* make reflectance a function of roughness by default and for on-the-fly generated shaders as well
* allow up to 4K shadowmaps
* increase the number of samplers so that we can use the authoring übershaders
N/A
These changes alter specular response mildly. 
N/A
Manual 💁‍♂️
Used GltfViewer and the damanged helmet asset to check for regressions and see if the additions work as intended.

[GFX-807] Migrate GltfViewer changes back to Shapr3D Filament fork

---

filament/backend/include/backend/DriverEnums.h

[https://shapr3d.atlassian.net/browse/GFX-807](https://shapr3d.atlassian.net/browse/GFX-807)
Metal validation layer does not allow us to go over the 16 sampler limit so we have to undo that change. 
n/a
n/a
n/a
Manual 💁‍♂️
Ran Shapr3D in Visualize Tool and compared this library candidate with the current one on master. 
Automated 💻
n/a

Filament [GFX-807] Fix filament Metal lib

---

filament/include/filament/Skybox.h
filament/src/Skybox.cpp
filament/src/details/Skybox.h
filament/src/materials/skybox.mat
libs/viewer/src/SimpleViewer.cpp

[GFX-848](https://shapr3d.atlassian.net/browse/GFX-848)
Added a checkerboard generation function, and screen space pixel position based usage of it in `skybox.mat` and related C++ code.
Note that Filament's tone mapping blends the patterns corners slightly. I don't think it's visible/noticeable in 1:1 zoom, but here's an example with a 19x zoom.
Not applicable yet
Filament skybox-related code
gltf viewer environments, no shapr changes
Manual 💁‍♂️
Using gltf viewer, set the environment type to the new "Checkerboard" option.

[GFX-848] Add checkerboard generation support to the modified skybox material in Filament

---

filament/include/filament/Skybox.h
filament/src/Skybox.cpp
filament/src/details/Skybox.h
filament/src/materials/skybox.mat

[GFX-893](https://shapr3d.atlassian.net/browse/GFX-893)
Shapr uses a Z-up coordinate system, while Filament uses a Y-up one. This means our gradient skybox shader looking fine (having a vertical gradient) in gltf viewer, will not look as intended (the gradient will be horizontal) in Shapr.
Edit: We decided to use a runtime uniform variable to switch between the two, to be able to handle both cases without Filament rebuilds. The default behaviour is Y up. See https://github.com/shapr3d/filament/pull/13/commits/460d1516f80e16571179f7858856fcb0ef22f96a
N/A
Gradient environment rendering
N/A
Manual 💁‍♂️
The gradient is now horizontal in gltf viewer.

Filament [GFX-893] Change gradient direction from Y to Z for Shapr (will break gltf viewer)

---

filament/include/filament/Skybox.h
filament/src/Skybox.cpp
filament/src/details/Skybox.h
filament/src/materials/skybox.mat

[GFX-828](https://shapr3d.atlassian.net/browse/GFX-828)
We need some iterations on the looks of the gradient and checkerboard pattern backgrounds. Adding uniform variables allows us to iterate on them without needing Filament bumps in the Shapr repository.
N/A
Filament's skybox material
N/A
Manual 💁‍♂️
Looked at gltf viewer by hand.

[GFX-828] Add checkerboard grays, gradient settings uniforms to Filament's skybox

---

filament/src/materials/skybox.mat

[GFX-925](https://shapr3d.atlassian.net/browse/GFX-925)
Gradients got burnt out when very saturated colours were chosen. See screenshot.
The root cause was color components close to 0 becoming negative, if another component was close to 1, which caused color grading to fail.
N/A
Visualization tool gradient environment
Visualization tool gradient environment with very saturated colours
Manual 💁‍♂️
Tried problematic colors, looked fine.

Filament [GFX-925] Disallow color components to get out of 0..1 range

---

third_party/clang/iOS.cmake

-
`json.hpp`, used by gltf viewer's library, `libviewer` uses `std::filesystem::path`, which was introduced in iOS 13.0 SDK. We need to bump to this version, to avoid build errors.
N/A
Filament custom fork builds with `<source root>/libs/filament/create_pkg.sh`
Just try to build, and it should succeed
Manual 💁‍♂️
Ran the script, build succeeded

Filament - Bump iOS deployment target to 13.0

---

libs/viewer/include/viewer/SimpleViewer.h
libs/viewer/include/viewer/TweakableMaterial.h
libs/viewer/include/viewer/TweakableProperty.h
libs/viewer/src/SimpleViewer.cpp
libs/viewer/src/TweakableMaterial.cpp

[GFX-991](https://shapr3d.atlassian.net/browse/GFX-991)
Artists have been providing us bugos assets for a while now. Adding some measures to counteract them. The only missing one is the 16bpc input textures, for which I haven't found a trivial way to detect without changing STB interfaces. 
Changelist:
[Added] Error messages on incorrect texture channel counts
[Added] More explicit conversion to expected channel counts from the one
found in the texture (maybe this will uncover some extra issues)
[Added] Texture format to string conversion array
[Changed] The default of IsColor is now FALSE on everything (artists
need to validate this on all released materials!)
[Fixed] Occlusion intensity was handled as if it was textures, which is
incorrect, it is a scalar attribute
n/a
GltfViewer …

GltfViewer [GFX-991] Texture validation functions

---

libs/camutils/src/FreeFlightManipulator.h
libs/camutils/src/Manipulator.cpp
libs/filagui/src/ImGuiExtensions.cpp
libs/filamentapp/src/FilamentApp.cpp
libs/viewer/src/SimpleViewer.cpp

[GFX-994](https://shapr3d.atlassian.net/browse/GFX-994)
Filament's certain aspects (especially the so-called froxelizer) expect the Y axis to be the upwards direction. We changed it to be the Z axis, to match Shapr3D's coordinate system. We revert it, hoping some of our issues get fixed, and get closer to upstream Filament.
N/A
Filament, gltf viewer
N/A
Manual 💁‍♂️
Models are now rotated in gltf viewer, apart from that, they look fine.

[GFX-994] Revert Filament's coordinate system to Y-up

---

filament/backend/src/metal/MetalBuffer.mm
filament/backend/src/metal/MetalDriver.mm
filament/include/filament/IndexBuffer.h
filament/include/filament/VertexBuffer.h

[GFX-1101](https://shapr3d.atlassian.net/browse/GFX-1101)
Small correction continuing https://github.com/shapr3d/filament/pull/1. External index/vertex buffers should do bridging with ownership transfer, in order to ensure that the `id<MTLBuffer>` resource is kept alive from the moment a vertex/index buffer object is created on the frontend, to when it is processed by the driver thread. This makes external buffer handling aligned with external resources semantics existing upstream, namely in [`Texture::Builder::import()`](https://github.com/google/filament/blob/5dba7fdae0ae1e700d5f987d106d52c0e95a1835/filament/include/filament/Texture.h#L212).

[GFX-1101] Pass external buffers with ownership transfer in Metal

---

shaders/src/shading_parameters.fs

[GFX-1098](https://shapr3d.atlassian.net/browse/GFX-1098)
Our normal maps don't look good on some faces. There are three root causes:
- By having our normal maps projected "through" the geometry (see diagram, this is closer to the real "volumetric" property of materials), we horizontally flip the normal map on some faces. This also flips the X coordinate of the tangent space normal, which we need to account for. 
- Filament applies a root transform to the entire scene, when the IBL has a rotation transform applied. This makes an unexpected switch in the coordinate system in Visualization compared to Model Space.
- Filament expects normals in tangent space, but our triplanar mapping produces world space results. Thus we need to transform our results back to tangent space, just for Filament …

[GFX-1098] Add toggle for disabling double transform TS<->WS

---

filament/src/Renderer.cpp
filament/src/materials/colorGrading/colorGrading.mat
shaders/src/light_indirect.fs
shaders/src/shading_lit.fs

[GFX-1161](https://shapr3d.atlassian.net/browse/GFX-1161)
This PR fixes issues with certain transparent materials, possible when rendered against a background cleared to transparent (all zeros).
First, we adjust color grading (in the `!POST_PROCESS_OPAQUE` case) so that it outputs a visible fragment when input alpha is zero but RGB values are not. Given that our color render target is treated as containing colors with premultipled alpha, these values should be considered invalid - however certain materials may produce such output, (visible on screen), for example a material with `blending: transparent` and `baseColor.a = 0`.
Second, we allow for screen-space refractive materials to output transparent results. We retain the alpha channel of the blitted color texture, sample it in shader, …

[GFX-1161] Improve transparent materials rendered in translucent views

---

filament/src/materials/Cloth.mat
filament/src/materials/MaterialHelpersShading.fxh
filament/src/materials/Opaque.mat
filament/src/materials/Refractive.mat
filament/src/materials/Subsurface.mat
filament/src/materials/Transparent.mat

[GFX-1147](https://shapr3d.atlassian.net/browse/GFX-1147)
This is an urgent PR as the last GltfViewer broke the appearance of all materials that used normal or clearcoat normal maps;
Turns out, we managed to test the last changes on planar surfaces where this is wasn't visible and on materials that did not have normal maps but were assigned to spheres.
It seems like the fixes to normal maps were partial in a recent change. I have taken the latest, Shapr3D master state of the material shaders and added and validated in GltfViewer that it is fixing the issues and brings the shaders to the same state.
n/a
GltfViewer normal mapped materials
normal mapped materials from https://e.pcloud.link/publink/show?code=kZ8cnJZoDyl4918RRf9E4lN6FKMCBckTmU7
Manual 💁‍♂️
Load up materials in GtlfViewer, …

[GFX-1147] Integrate triplanar changes from Shapr3D into this repo

---

filament/src/materials/MaterialHelpersShading.fxh

[GFX-1206](https://shapr3d.atlassian.net/browse/GFX-1206)
The normal mapping fix has accidentally applied normal intensity in world space instead of doing it in tangent space. This PR is fixing this issue that created exaggerated reflections.
Before this fix and after the normal mapping fix we had this:
Witht his current PR, you'll get back the proper looks as
The screenshots were taken with polished iron. The tricky thing with this bug was that normally, you wouldn't notice these as long as normal intensities stayed close to 1.0. Luckily, art made some really brave adjustments to these variables that pronounced this effect much more .
n/a
Visualization materials
You'll mostly see this on highly reflective materials that have surface complexity. An example is polished iron.
Manual 💁‍♂️
Go …

[GFX-1206] Fixed normal intensity

---

shaders/src/main.vs

[GFX-988](https://shapr3d.atlassian.net/browse/GFX-988)
This is the Filament counterpart of https://github.com/shapr3d/shapr3d/pull/9197. Even though it is not strictly required, because Filament's mesh import takes care of computing a good tangent frame, this makes the tangent frame identical to that in Shapr3D, easing the artists' work.
N/A
gltf viewer mesh tangent frames
Materials in gltf viewer
Manual 💁‍♂️
Looked at the test scene with some materials, and a debug coloring showing the tangents

[GFX-988] Implement Frisvad tangent computation

---

filament/src/materials/MaterialHelpersShading.fxh
filament/src/materials/Transparent.mat

[GFX-1206](https://shapr3d.atlassian.net/browse/GFX-1206)
[GFX-1214](https://shapr3d.atlassian.net/browse/GFX-1214)
Filament counterpart of 
1. https://github.com/shapr3d/shapr3d/pull/9243 (ambientOcclusion)
2. https://github.com/shapr3d/shapr3d/pull/9241 (transparent should be double sided)
n/a
See https://github.com/shapr3d/shapr3d/pull/9243 
See https://github.com/shapr3d/shapr3d/pull/9243
Manual 💁‍♂️
You need to touch all of our .mat files to be able to test ambientOcclusion fix in the GltfViewer.
Automated 💻
n/a

[GFX-1206] Saturate ambientOcclusion and fix transparent

---

filament/src/ResourceAllocator.cpp

[GFX-1162](https://shapr3d.atlassian.net/browse/GFX-1162)
Filament only creates render target textures for the lifetime of one frame. The cost of actual allocations are kept low by employing a cache in frontend (`filament::ResourceAllocator`). This texture pool has a fixed 150MB capacity cap, which is most often enough, although multisampling and near-4K resolutions can outgrow it. If a renderer operates above said limit, it inevitably leads to reallocation of textures in every frame.
This PR aims to prevent thrashing in those occasions, by keeping textures in cache which were used in the last frame, even if that means staying above cache size limits.
Memory usage, texture allocations
Manual 💁‍♂️
Checked allocation timelines in Instruments on Metal Game Performance template.

[GFX-1162] Retain most recently used textures in resource cache

---

CMakeLists.txt

[GFX-1223](https://shapr3d.atlassian.net/browse/GFX-1223)
Apparently we can get usable stack traces by just enabling generation of stack unwind tables on iOS. We don't need to enable C++ exceptions. We still lost parts of the stack trace, but at least [the stack frame above](https://console.firebase.google.com/u/0/project/shapr3d-mac/crashlytics/app/ios:com.shapr3d.shapr.beta/issues/3866f5d174dfc83bf7a643f54d32537a?time=last-twenty-four-hours&types=crash&sessionEventKey=e0ca35756cdf4479ab4173d3459ea225_1648214803643439505) `panic` is preserved giving us a chance to understand (and group) Filament related crashes.
Crash report, before: 
Crash report (of the same crash), after:
FYI, #40 couldn't preserve the entire stack trace either, but [only the frame …

[GFX-1223] Generate stack unwind tables 

---

filament/src/materials/Cloth.mat
filament/src/materials/MaterialHelpersShading.fxh
filament/src/materials/Opaque.mat
filament/src/materials/Refractive.mat
filament/src/materials/Subsurface.mat
libs/viewer/include/viewer/TweakableMaterial.h
libs/viewer/src/SimpleViewer.cpp
libs/viewer/src/TweakableMaterial.cpp

[GFX-1265](https://shapr3d.atlassian.net/browse/GFX-1265)
(EDIT Note: this will be followed up by a Shapr PR.)
The initial premise of the Cloth changes was that all fabrics with black `baseColor` looked completely flat, as if no shading was applied. The solution to this issue has two aspects:
* First, these materials should use derivable sheen colors. 
* Second, we have to clamp the almost-black colors to a reasonably dark gray, and re-normalize the very dark (but not almost black) colors 
I've tried to avoid hue shifts by using re-normalization but that would still need a special case around (0,0,0) color arguments (and denormals, for that matter) so I'm just clamping the result of the sqrt independently (i.e., per component) to some epsilon that was chosen such that an Opaque shader …

[GFX-1265] Improve Cloth and Subsurface shading

---

filament/include/filament/IndirectLight.h
filament/include/filament/Options.h
filament/src/IndirectLight.cpp
filament/src/PerViewUniforms.cpp
filament/src/PerViewUniforms.h
filament/src/View.cpp
filament/src/details/IndirectLight.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
libs/viewer/include/viewer/Settings.h
libs/viewer/src/Settings.cpp
libs/viewer/src/SimpleViewer.cpp
shaders/src/light_indirect.fs
shaders/src/main.vs
shaders/src/shading_lit.fs

[GFX-610](https://shapr3d.atlassian.net/browse/GFX-610)
This PR is the fixed version of https://github.com/shapr3d/filament/pull/44 . That had to be reverted, because anisotropic shading was applied incorrectly. We referred to these as Interstellar shading:
This was fixed in two steps. First, none of the shading paths should use anisotropicity except for the direct IBL specular. This required a refactor, done in https://github.com/shapr3d/filament/commit/828f39066883c3db3e830d5c41348d5b5261b513 .
Second, a bug had to be fixed in the Frisvad tangent computation on the GltfViewer side in https://github.com/shapr3d/filament/commit/48c3207d0b645b464463df2b0e25041fbf5ba11b . This only affected the GltfViewer. 
n/a (and see previous PR)
Visualization IBL reflections and GltfViewer
As previously …

[GFX-610] Fix integration of box and sphere IBLs

---

filament/include/filament/TransformManager.h

[KRN-77](https://shapr3d.atlassian.net/browse/KRN-77)
This PR replaces `std::iterator<>` (deprecated in cpp17) with a different implementation, so we can eventually upgrade to Xcode 13.3
N/A
N/A
N/A
Manual 💁‍♂️
❌ 
Automated 💻
❌

[KRN-77] Comply with cpp17 deprecations

---

CMakeLists.txt
filament/backend/src/HandleAllocator.cpp

[GFX-547](https://shapr3d.atlassian.net/browse/GFX-547)
We've investigated the implications of changing the buffer size parameters in the root CMakeLists.txt. You can read the findings [here](https://shapr3d.atlassian.net/wiki/spaces/DD/pages/2868347235/Filament+findings#Setting-buffer-sizes). 
n/a
Size of `HandleArena` in Filament.
* Load huge models.
* Check if you get any of these errors:
* `CommandStream used too much space: `_`» total used memory amount here «`_` out of 51380224 (will block)`
* `HandleAllocator arena is full, using slower system heap. Please increase the appropriate constant (e.g. FILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB).`
Manual 💁‍♂️
See Confluence doc for measurements.
Automated 💻
n/a

[GFX-547] Set buffer sizes in root CMakeLists.txt

---

filament/src/materials/separableGaussianBlur.mat
shaders/src/light_indirect.fs

[GFX-1463](https://shapr3d.atlassian.net/browse/GFX-1463)
Bug ticket was created, that screenshot in transparent environment is broken in case of PP material. The first issue was that `separableGaussianBlur` was outputting a `vec3`, so it had no alpha channel, resulting invalid values. It was easily fixed by modifying it to output a `vec4` instead.
However, since we're clearing the background to `vec4(0,0,0,0)`, this resulted in the following behavior:
While this is how the same scene looks like in case of a white solid background:
The value is computed as follows: we render the opaque objects first. Then in `applyRefraction`, we read the color of the pixel into `Ft`, and the alpha to `at`, then the modulate their value using physics. The final `Ft` and `at` contributes to the final …

[GFX-1463] Fix Transparent Screenshot

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h
filament/backend/src/metal/MetalState.h
filament/backend/src/metal/MetalState.mm
filament/backend/src/opengl/GLUtils.h
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/include/filament/Material.h
filament/include/filament/MaterialInstance.h
filament/src/Material.cpp
filament/src/MaterialInstance.cpp
filament/src/MaterialParser.cpp
filament/src/MaterialParser.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/details/Material.h
filament/src/details/MaterialInstance.h
libs/filabridge/include/filament/MaterialChunkType.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/matdbg/src/JsonWriter.cpp
libs/matdbg/src/TextWriter.cpp
tools/matc/src/matc/ParametersProcessor.cpp

[GFX-999](https://shapr3d.atlassian.net/browse/GFX-999)
This PR introduces the almost minimal functionality to filament materials to enable us create the selection outline.
The material API was extended with `stencilWrite`, `stencilDepthFail`, `stencilDepthPass` settings.
These options control both the back and front face stencil test operations. For simplicity the stencil test always succeeds (if enabled with `stencilWrite`) and the reference value fixed to 1.
| Settings  | Valid values |
| ------------- | ------------- |
| `stencilWrite`  | `true` `false` |
| `stencilDepthFail`  | `keep` `zero` `invert` `replace`  |
| `stencilDepthPass`  | `keep` `zero` `invert` `replace`  | 
n/a
OpenGL backend, Metal backend, Material API, Material parser
n/a
Manual 💁‍♂️
Run it on my local machine …

[GFX-999] Filament stencil operations

---

filament/include/filament/Renderer.h
filament/include/filament/View.h
filament/src/Renderer.cpp
filament/src/View.cpp
filament/src/details/Renderer.h
filament/src/details/View.h
libs/viewer/src/Settings.cpp
samples/lightbulb.cpp
samples/material_sandbox.cpp
samples/rendertarget.cpp

[GFX-1109](https://shapr3d.atlassian.net/browse/GFX-1109)
The View's API was extended with HDR color and depth-stencil output textures. The already existing RenderTarget API was kept, because the IBL pre-filtering used it. The depth-stencil output texture contains the resolved texture if hardware supports the operation otherwise the multisample texture.
n/a 
Filament's frame graph building, metal backend
Multisampling, post processing
Manual 💁‍♂️
I experimented with the `rendertarget` sample-project.
Automated 💻
n/a

[GFX-1109] External depth buffering

---

tools/matc/src/matc/ParametersProcessor.cpp

[GFX-1555](https://shapr3d.atlassian.net/browse/GFX-1555)
`depthStencilPass` and `depthStencilFail` produced material compiler errors, because the parser's result was inverted.
n/a
Material compiler, parser
n/a
Manual 💁‍♂️
I checked with a modified version of `matc_test`
Automated 💻
n/a

[GFX-1555] depthStencilPass, depthStencilFail parameter parsing bug fixed

---

filament/backend/src/metal/MetalBlitter.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalState.h
filament/backend/src/metal/MetalState.mm
filament/src/Renderer.cpp

[GFX-1555](https://shapr3d.atlassian.net/browse/GFX-1555)
This is purely technical PR. Metal backend was extended to handle properly stencil attachments in case of packed depth-stencil texture formats (OpenGL and Vulkan backend already supported separate and packed depth and stencil attachments). The depth attachment was renamed according to the new use case. This PR's modifications don't address the hardware support part of the stencil resolve.
n/a
Filament metal backend
n/a
Manual 💁‍♂️
https://github.com/shapr3d/filament/pull/55 test based on this implementation.
Automated 💻
n/a

[GFX-1555] External stencil buffering

---

libs/matdbg/src/CommonWriter.h
tools/matc/src/matc/ParametersProcessor.cpp

N/A
Recent depth-stencil changes broke Windows compilation of GltfViewer. One was caused by a missing <optional> include (may be hidden by differences in VS2002/2019) and the other is due to two missing toString calls. This PR adds these. 
n/a
GltfViewer on Windows
Compile and run GltfViewer on Windows.
Manual 💁‍♂️
As above
Automated 💻
n/a

[Fixed] Windows sample and GltfViewer compilation

---

filament/backend/src/metal/MetalEnums.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalState.mm

[GFX-1597](https://shapr3d.atlassian.net/browse/GFX-1597)
One of the Stencil format is not supported on all platforms, so the previous changes to filament now generate compile errors.
n/a
Filamentt build (iOS)
n/a
Manual 💁‍♂️
Just run the create_pkg.sh
Automated 💻
n/a

[GFX-1597] iOS build error fix

---

filament/backend/src/metal/MetalBlitter.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalState.h
filament/backend/src/metal/MetalState.mm

[GFX-1596](https://shapr3d.atlassian.net/browse/GFX-1596)
Quick fix for filament's depth blit backend. Filament's depth blit doesn't use the stencil buffer, but the pipeline marked it as used, which resulted in a Metal error.
n/a
n/a
n/a
Manual 💁‍♂️
Repro: Disable automatic resolve and create an MSAA depth texture in the frame graph (preferably in corollas) and use the PostProcessManager::resolve() function on it. 
Automated 💻
n/a

[GFX-1596] Stencil depth blit fix

---

filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.mm

[GFX-1566](https://shapr3d.atlassian.net/browse/GFX-1566)
The depth bias values cached now in MetalContext. The driver will insert the depth bias set command in the command buffer, if it differ from the cached ones, this minimise the setDepthBias calls and resets properly the bias, when the driver encounters a geometry with a non depth bias material instance.
n/a
Filament rendering, Metal backend
n/a
Manual 💁‍♂️
n/a
Automated 💻
Run the rendertests with a low threshold (0.5). There was no deviations in the visualization images (all epsilon = 0).

[GFX-1566] Fix skipped depth bias set in Metal backend

---

filament/src/VertexBuffer.cpp

[GFX-1565](https://shapr3d.atlassian.net/browse/GFX-1565)
The problem was that filament doesn't know, where the attribute located in the stride, so it calculated the required buffer-size as the attribute would be the first member of the interleaved datatype.
n/a
Vertex buffer creation, model loading
n/a
Manual 💁‍♂️
Checked with `rendertarget` sample project and with a Shapr3D workspace.
Automated 💻
n/a

[GFX-1565] Vertex buffer-size fix.

---

filament/backend/include/backend/MetalPlatform.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalPlatform.mm

[GFX-1438](https://shapr3d.atlassian.net/browse/GFX-1438)
@veghbalazs modified the filament's metal backend to enable us inject any custom metal render command encoder. The injection can be achieved by overloading the createRenderCommandEncoder virtual function of the MetalPlatform class.
Manual 💁‍♂️
Automated 💻

[GFX-1438] Custom render command encoder injection

---

filament/include/filament/Renderer.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h

[GFX-789](https://shapr3d.atlassian.net/browse/GFX-789)
The stale `endFrame()` call was a hacky solution that we got away with on Apple platforms but won't on Windows.
`Renderer::endFrame()` -> `FrameInfoManager::endFrame()` -> `OpenGLDriver::endTimerQuery()` will crash in ANGLE, because you cannot end a query without starting any. This didn't cause problems in the Metal backend.
Wherever I put the garbage collection code, `PhysicallyBasedRenderer::Impl::Clear()` must access it. So I chose to add a new public method in Filament renderer. I chose not to call this new function from `renderStandaloneView()` because I feel it doesn't belong there (what if I want to render multiple views before performing a GC?)
Manual 💁‍♂️
Automated 💻

[GFX-789] Add garbage collection of Engine to public API

---

filament/src/Texture.cpp
libs/utils/include/utils/compiler.h

[GFX-593](https://shapr3d.atlassian.net/browse/GFX-593)
This PR contains a few changes necessary to get offscreen rendering up and running on Windows with ANGLE.
We use some OpenGL objects from both `PhysicallyBasedRenderer` and the OpenGL backend of Filament. This is needed to share the vertex/index buffer and the presentable texture between Gfx and Filament. However OGL objects belong to OGL contexts [which are thread local](https://www.khronos.org/opengl/wiki/OpenGL_Context):
> In order for any OpenGL commands to work, a **context must be current**... . The current **context is a thread-local** variable... . However, a single context **cannot be current in multiple threads** at the same time.
I chose to disable threading in Filament (Windows only!) as a quick fix and created [a …

[GFX-593] Preparations for Windows rendering 

---

filament/backend/include/private/backend/DriverAPI.inc
filament/backend/include/private/backend/OpenGLPlatform.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/PlatformCocoaGL.h
filament/backend/src/opengl/PlatformCocoaGL.mm
filament/backend/src/opengl/PlatformCocoaTouchGL.h
filament/backend/src/opengl/PlatformCocoaTouchGL.mm
filament/backend/src/opengl/PlatformDummyGL.h
filament/backend/src/opengl/PlatformEGL.cpp
filament/backend/src/opengl/PlatformEGL.h
filament/backend/src/opengl/PlatformGLX.cpp
filament/backend/src/opengl/PlatformGLX.h
filament/backend/src/opengl/PlatformWGL.cpp
filament/backend/src/opengl/PlatformWGL.h
filament/backend/src/opengl/PlatformWebGL.cpp
filament/backend/src/opengl/PlatformWebGL.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/Renderer.cpp
libs/utils/include/utils/compiler.h

[GFX-1741](https://shapr3d.atlassian.net/browse/GFX-1741)
For faster development previously we disabled threading in Filament, because the `OpenGL` backend wasn't prepared for the way we used it as an offscreen renderer. The resources were created on `Shapr3D`'s renderer thread, but was used in Filament on another thread, which only permitted according to the `OpenGL` specs, if the `OpenGL` context are shared between the threads. To re-enable multithreading, changes were made to the backend to make the thread current, on which the driver commands are executed. 
Furthermore an issue with `EGLDisplay`'s lifetime ownership was addressed: from now on Filament doesn't own the display.
n/a
Offscreen rendering
n/a
Manual 💁‍♂️
Checked on my local Windows 10 machine, with the modification on the …

[GFX-1741] Re-enable multithreading

---

filament/src/materials/Cloth.mat
filament/src/materials/Opaque.mat
filament/src/materials/Refractive.mat
filament/src/materials/Subsurface.mat

n/a
The doublesided rendering tag was only added in the Shapr3D repo to the materials. This PR backports those changes to the source repo.
n/a (Shapr only changes)
n/a
n/a
n/a
Manual 💁‍♂️
n/a
Automated 💻
n/a

[Added] Missing doublesided annotations

---

filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLProgram.cpp
filament/src/PostProcessManager.cpp
filament/src/ShadowMap.cpp
filament/src/VertexBuffer.cpp
libs/filamentapp/include/filamentapp/MeshAssimp.h
libs/image/include/image/ColorTransform.h
libs/math/tests/test_half.cpp
libs/utils/include/utils/Allocator.h
libs/utils/include/utils/BinaryTreeArray.h
libs/utils/include/utils/FixedCapacityVector.h
libs/utils/include/utils/SingleInstanceComponentManager.h
libs/utils/include/utils/StructureOfArrays.h
libs/utils/include/utils/compiler.h
libs/utils/src/JobSystem.cpp
libs/utils/src/Profiler.cpp
libs/viewer/include/viewer/AutomationEngine.h
tools/specular-color/src/main.cpp

[GFX-1868](https://shapr3d.atlassian.net/browse/GFX-1868)
We already fixed some MSVC warnings in #75 which was further optimized in #83. This got us so far that we could make an internal build with Vis. on Windows. But Filament contained many more public headers which we may not be using right now, but might need anytime in the future.
This PR fixes all W3 level MSVC warnings in the remaining public headers, regardless if it is used in Shapr or not.
[GFX-1891](https://shapr3d.atlassian.net/browse/GFX-1891)
n/a
n/a
n/a
Manual 💁‍♂️
I tested on VS2019 and V2022 with a .cpp file that includes all public headers of Filament (except for Apple/Linux only). You can test it too with https://github.com/shapr3d/shapr3d/tree/palver123/GFX-1868_filament_warnings_test (just have to change the path of …

[GFX-1868] Fix W3 level MSVC warnings in public headers

---

libs/utils/src/JobSystem.cpp

[GFX-2038](https://shapr3d.atlassian.net/browse/GFX-2038)
Apply thread names (`FEngine::loop`, `JobSystem::loop`) on Windows, useful in debuggers and crash dumps.  
Debugging for [GFX-2017](https://shapr3d.atlassian.net/browse/GFX-2017) required me finding Filament driver thread in Visual Studio. 
My intention is to open an upstream PR right after getting approved here.
Thread initialization on Windows.
n/a
Manual 💁‍♂️

[GFX-2038] Implement setThreadName() on Windows

---

filament/src/components/RenderableManager.cpp

[GFX-2063](https://shapr3d.atlassian.net/browse/GFX-2063)
Turn off flushing in `RenderableManager::create()`. We have to guarantee mutually exclusive access to a shared device context between Shapr3D and Filament, which means adding fences following any Filament API call which flushes the command queue. Fence on each and every `AddPart()` call would be too expensive, let's turn off the flushing heuristic here instead. This is a quickfix, we'll rethink our threading on Windows in a future card.
Not applicable, we hope to revert this in [GFX-2274](https://shapr3d.atlassian.net/browse/GFX-2274).
n/a
Entity creation, command queueing.
n/a
Manual 💁‍♂️
Loaded a large model in Visualization to prove that flushing can be safely deferred to the point of first draw. 
Automated 💻
Shapr3D rendertests …

[GFX-2063] Don't flush on renderable creation

---

filament/src/materials/ssao/ssct.fs
libs/filamat/src/GLSLPostProcessor.cpp

[GFX-2225](https://shapr3d.atlassian.net/browse/)
When we disabled the shader optimisations in Filament a lot of unused variable warning appeared and bloated the output. After multiple prototypes (filter it with defines, spirv-cross reflection), we decided to run with a simple find and replace (insert) solution for the warnings. The following code lines (after metal transcompilation) introduce the majority of the unused variable warnings:
```
float3x3 shading_tangentToWorld;
float3 shading_position;
float3 shading_view
float3 shading_normal;
float3 shading_geometricNormal;
float3 shading_reflected;
float shading_NoV;
float2 shading_normalizedViewportCoord;
float3 shading_clearCoatNormal;
float filament_lodBias = frameUniforms.lodBias;
float level0 = fast::clamp(floor(log2(ssSliceRadius)) …
```

[GFX-2225] Handle Metal shader unused variable warnings

---

filament/include/filament/Options.h
libs/viewer/src/SimpleViewer.cpp
shaders/src/light_indirect.fs

[GFX-1630](https://shapr3d.atlassian.net/browse/GFX-1630)
While making the Filament upstream PR, a spherical IBL lookup optimization was added. If we assume that the lookup position is within the sphere, we can simplify the ray-sphere intersection computations. If the lit fragment is outside of the sphere however, we'll have different shading. This should not be a problem for Shapr, since we guarantee there that the sphere is large enough to contain the workspace. 
Previously, this is what happened when your IBL sphere did not include the entirety of the scene:
With the ray-sphere intersection code introduced in this PR, the out-of-sphere lookups will be changed such as this:
The previous implementation (that computed both roots in a numerically stable way) required 42 full rate and 3 …

[GFX-1630] Optimize spherical IBL lookup

---

filament/backend/src/metal/MetalEnums.mm

[GFX-2246](https://shapr3d.atlassian.net/browse/GFX-2246)
I must have missed sth in https://github.com/shapr3d/filament/pull/3/commits/8d6ef7682b1806c1f56761c7fa8fb9f4b1972786 because the iPad 10.5" Simulator seems to support ASTC. I found this out while testing my code before opening an upstream PR. Turned out I could run rendering tests with ASTC textures after removing the check from Filament.
(My guess is that I mistook a Filament error message to a Metal API Validation error message)
I briefly tested ETC2 too and I verified that I can indeed create such a texture on iOS Simulator and update its content (with valid ETC2 compressed data). I didn't do further testing (such as can it be bound to a fragment shader, can a shader actually sample it etc...).
Nothing. In fact, the upstream …

[GFX-2246] Enable ASTC on Simulator
